x-images: &images
  base: &base-image naylence/agent-sdk-python:0.2.1

services:
  # Sentinel service - runs the central coordinator on port 8000
  sentinel:
    image: *base-image
    volumes:
      - .:/work:ro
    working_dir: /work
    command: ["python", "sentinel.py"]
    ports:
      - "8000:8000"
    networks:
      - naylence-net
    stop_signal: SIGINT
    stop_grace_period: 1s
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 8000)); s.close()"]
      interval: 0.5s
      timeout: 1s
      retries: 10
      start_period: 0.5s
      start_interval: 1s

  # Chat Agent service - connects to sentinel and provides chat functionality
  chat-agent:
    build: .
    volumes:
      - .:/work:ro
    working_dir: /work
    command: ["python", "chat_agent.py"]
    depends_on:
      sentinel:
        condition: service_healthy
    networks:
      - naylence-net
    environment:
      - FAME_DIRECT_ADMISSION_URL=ws://sentinel:8000/fame/v1/attach/ws/downstream
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  #   restart: unless-stopped

networks:
  naylence-net:
    driver: bridge
