x-images: &images
  base: &base-image naylence/agent-sdk-python:0.3.12

services:
  # Sentinel service - runs the central coordinator on port 8000
  sentinel:
    image: *base-image
    volumes:
      - .:/work:ro
    working_dir: /work
    command: ["python", "sentinel.py"]
    ports:
      - "8000:8000"
    networks:
      - naylence-net
    stop_signal: SIGINT
    stop_grace_period: 1s
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 8000)); s.close()"]
      interval: 0.5s
      timeout: 1s
      retries: 10
      start_period: 0.5s
      start_interval: 1s
    environment:
      - FAME_DELIVERY_PROFILE=${FAME_DELIVERY_PROFILE:-at-most-once}
    

  # Message Agent service - connects to sentinel and provides message functionality
  message-agent:
    image: *base-image
    volumes:
      - .:/work
    working_dir: /work
    command: ["python", "message_agent.py"]
    depends_on:
      sentinel:
        condition: service_healthy
    networks:
      - naylence-net
    env_file: ./config/.env.agent

    restart: on-failure

networks:
  naylence-net:
    driver: bridge
